### ISSUE TITLE
Navigation tabs only show for administrators

### ISSUE THREAD

**Issue by phuicy** [aki360P/redmine_resource_booking_system#3]
Navigation tabs only show for administrators for booking or settings.

**Comment by aki360P** [comment]
Permission depends on default permission setting. Please check the "Roles and permissions" setting.
![rrbs_permission](https://user-images.githubusercontent.com/34680805/60749697-93076b00-9fd8-11e9-90e3-7e9ae7b6c3b9.png)

**Comment by phuicy** [comment]
Thanks. It might be worth putting that in the documentation.
