### ISSUE TITLE
Issue after installation

### ISSUE THREAD

**Issue by mkaminski9193** [aki360P/redmine_resource_booking_system#4]
Hey,

I'm running Redmine 4.0.4 with Ruby 2.5.1p57 on Ubuntu 18.04. I tried to download plugin called redmine resource booking system. I went through installation process from https://www.redmine.org/plugins/redmine_resource_booking_system.
This plugin is visible in project when i enabled it however i got Internal Error 500.
When i opened log file i found this error:
*Completed 500 Internal Server Error in 18ms (ActiveRecord: 4.0ms)
NoMethodError (undefined method `possible_vaules' for nil:NilClass):
plugins/redmine_resource_booking_system/app/controllers/rrbs_bookings_controller.rb:18:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'*

Thanks in advance

**Comment by aki360P** [comment]
Hi,
Please complete plugin setting.  Github document may be more useful. please refer to https://github.com/aki360P/redmine_resource_booking_system

And don't forget to give permission to users.
![rrbs_permission](https://user-images.githubusercontent.com/34680805/61129089-a0e45100-a4ee-11e9-908c-d79f08e7961c.png)
